//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitMe.Models.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuctionProductTable
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<int> SellerID { get; set; }
        public string SellerName { get; set; }
        public Nullable<int> BuyerID { get; set; }
        public string BuyerName { get; set; }
        public Nullable<decimal> WinnerBid { get; set; }
        public Nullable<System.DateTime> BidStartTime { get; set; }
        public Nullable<System.DateTime> BidEndTime { get; set; }
        public byte[] Image { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public string ProductCatagory { get; set; }
    }
}
