//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitMe.Models.Repositories
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BidMeDBEntities : DbContext
    {
        public BidMeDBEntities()
            : base("name=BidMeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuctionProductTable> AuctionProductTables { get; set; }
        public virtual DbSet<BrandTable> BrandTables { get; set; }
        public virtual DbSet<CategoryTable> CategoryTables { get; set; }
        public virtual DbSet<TagTable> TagTables { get; set; }
        public virtual DbSet<UserTable> UserTables { get; set; }
    
        public virtual int AddProduct(string pname, string pdes, byte[] ima)
        {
            var pnameParameter = pname != null ?
                new ObjectParameter("pname", pname) :
                new ObjectParameter("pname", typeof(string));
    
            var pdesParameter = pdes != null ?
                new ObjectParameter("pdes", pdes) :
                new ObjectParameter("pdes", typeof(string));
    
            var imaParameter = ima != null ?
                new ObjectParameter("ima", ima) :
                new ObjectParameter("ima", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddProduct", pnameParameter, pdesParameter, imaParameter);
        }
    
        public virtual int RegisterNewUser(string uNameparam, string uPasswordparam, string uEmailparam, string uAddress)
        {
            var uNameparamParameter = uNameparam != null ?
                new ObjectParameter("UNameparam", uNameparam) :
                new ObjectParameter("UNameparam", typeof(string));
    
            var uPasswordparamParameter = uPasswordparam != null ?
                new ObjectParameter("UPasswordparam", uPasswordparam) :
                new ObjectParameter("UPasswordparam", typeof(string));
    
            var uEmailparamParameter = uEmailparam != null ?
                new ObjectParameter("UEmailparam", uEmailparam) :
                new ObjectParameter("UEmailparam", typeof(string));
    
            var uAddressParameter = uAddress != null ?
                new ObjectParameter("UAddress", uAddress) :
                new ObjectParameter("UAddress", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RegisterNewUser", uNameparamParameter, uPasswordparamParameter, uEmailparamParameter, uAddressParameter);
        }
    
        public virtual ObjectResult<string> ReteiveAllBrand()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ReteiveAllBrand");
        }
    
        public virtual int RetreiveallCategory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RetreiveallCategory");
        }
    
        public virtual int RetrievAllUsername()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RetrievAllUsername");
        }
    }
}
