//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitMe.Models.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagTable
    {
        public int TagID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public string BrandName { get; set; }
        public Nullable<int> ProductID { get; set; }
    }
}
